-- MySQL Script generated by MySQL Workbench
-- Mon Jul  6 10:44:31 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Crowdex` DEFAULT CHARACTER SET utf8 ;
USE `Crowdex` ;

-- -----------------------------------------------------
-- Table `Crowdex`.`Currency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Crowdex`.`Currency` (
  `idCurrency` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NOT NULL,
  `ISO3` CHAR(3) NOT NULL,
  `Symbol` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`idCurrency`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Crowdex`.`Country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Crowdex`.`Country` (
  `idCountry` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NOT NULL,
  `ISO2` CHAR(2) NULL,
  `ISO3` CHAR(3) NULL,
  `Currency_idCurrency` INT NOT NULL,
  PRIMARY KEY (`idCountry`),
  INDEX `fk_Country_Currency1_idx` (`Currency_idCurrency` ASC) VISIBLE,
  CONSTRAINT `fk_Country_Currency1`
    FOREIGN KEY (`Currency_idCurrency`)
    REFERENCES `Crowdex`.`Currency` (`idCurrency`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Crowdex`.`City`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Crowdex`.`City` (
  `idCity` INT NOT NULL AUTO_INCREMENT,
  `Timezone` VARCHAR(20) NOT NULL,
  `Name` VARCHAR(255) NOT NULL,
  `Country_idCountry` INT NOT NULL,
  PRIMARY KEY (`idCity`),
  INDEX `fk_City_Country1_idx` (`Country_idCountry` ASC) VISIBLE,
  CONSTRAINT `fk_City_Country1`
    FOREIGN KEY (`Country_idCountry`)
    REFERENCES `Crowdex`.`Country` (`idCountry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Crowdex`.`Venue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Crowdex`.`Venue` (
  `idVenue` INT NOT NULL AUTO_INCREMENT,
  `City_idCity` INT NOT NULL,
  `Name` VARCHAR(255) NULL,
  `Address` VARCHAR(255) NOT NULL,
  `ZipCode` VARCHAR(255) NOT NULL,
  `Latitude` DECIMAL(9,6) NOT NULL,
  `Longitude` DECIMAL(9,6) NOT NULL,
  PRIMARY KEY (`idVenue`),
  INDEX `fk_Venue_City1_idx` (`City_idCity` ASC) VISIBLE,
  CONSTRAINT `fk_Venue_City1`
    FOREIGN KEY (`City_idCity`)
    REFERENCES `Crowdex`.`City` (`idCity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Crowdex`.`Event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Crowdex`.`Event` (
  `idEvent` INT NOT NULL AUTO_INCREMENT,
  `Venue_idVenue` INT NOT NULL,
  `Title` VARCHAR(150) NOT NULL,
  `Description` TEXT(65535) NULL,
  `StartDateTime` DATETIME NOT NULL,
  `EndDateTime` DATETIME NULL,
  `MinimumAge` TINYINT NULL,
  `Capacity` INT NULL,
  `BannerImage` VARCHAR(255) NULL,
  `TicketUrl` VARCHAR(255) NULL,
  `Status` ENUM("draft", "published", "cancelled", "postponed", "finished") NULL,
  `CreatedAt` TIMESTAMP NULL,
  `UpdatedAt` TIMESTAMP NULL,
  PRIMARY KEY (`idEvent`),
  INDEX `fk_Event_Venue1_idx` (`Venue_idVenue` ASC) VISIBLE,
  CONSTRAINT `fk_Event_Venue1`
    FOREIGN KEY (`Venue_idVenue`)
    REFERENCES `Crowdex`.`Venue` (`idVenue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Crowdex`.`Band`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Crowdex`.`Band` (
  `idBand` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(150) NOT NULL,
  `Description` TEXT(65535) NULL,
  `ProfileImage` VARCHAR(255) NULL,
  `CoverImage` VARCHAR(255) NULL,
  `FormedYear` YEAR NULL,
  `DisbandYear` YEAR NULL,
  `Verified` TINYINT NULL DEFAULT 0,
  `Website` VARCHAR(255) NULL,
  `SpotifyURL` VARCHAR(255) NULL,
  `YoutubeURL` VARCHAR(255) NULL,
  `InstagramUrl` VARCHAR(255) NULL,
  `FacebookUrl` VARCHAR(255) NULL,
  `TiktokUrl` VARCHAR(255) NULL,
  `CreatedAt` TIMESTAMP NULL,
  `UpdatedAt` TIMESTAMP NULL,
  PRIMARY KEY (`idBand`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Crowdex`.`Concert`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Crowdex`.`Concert` (
  `idConcert` INT NOT NULL AUTO_INCREMENT,
  `Band_idBand` INT NOT NULL,
  `Event_idEvent` INT NOT NULL,
  `Stage` VARCHAR(100) NULL,
  `StartDateTime` DATETIME NULL,
  `EndDateTime` DATETIME NULL,
  PRIMARY KEY (`idConcert`),
  INDEX `fk_Concert_Band1_idx` (`Band_idBand` ASC) VISIBLE,
  INDEX `fk_Concert_Event1_idx` (`Event_idEvent` ASC) VISIBLE,
  CONSTRAINT `fk_Concert_Band1`
    FOREIGN KEY (`Band_idBand`)
    REFERENCES `Crowdex`.`Band` (`idBand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Concert_Event1`
    FOREIGN KEY (`Event_idEvent`)
    REFERENCES `Crowdex`.`Event` (`idEvent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Crowdex`.`Genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Crowdex`.`Genre` (
  `idGenre` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idGenre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Crowdex`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Crowdex`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  `PFP` VARCHAR(255) NULL DEFAULT 'uploads/profile_pictures/default.webp',
  `Birthday` DATE NOT NULL,
  `Country_idCountry` INT NOT NULL,
  `Verified` TINYINT NULL DEFAULT 0,
  `Type` VARCHAR(45) NOT NULL DEFAULT 'User',
  `Username` VARCHAR(45) NOT NULL,
  `RememberToken` VARCHAR(64) NULL,
  PRIMARY KEY (`idUser`),
  INDEX `fk_User_Country1_idx` (`Country_idCountry` ASC) VISIBLE,
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
  CONSTRAINT `fk_User_Country1`
    FOREIGN KEY (`Country_idCountry`)
    REFERENCES `Crowdex`.`Country` (`idCountry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Crowdex`.`Band_has_Genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Crowdex`.`Band_has_Genre` (
  `Band_idBand` INT NOT NULL,
  `Genre_idGenre` INT NOT NULL,
  PRIMARY KEY (`Band_idBand`, `Genre_idGenre`),
  INDEX `fk_Band_has_Genre_Genre1_idx` (`Genre_idGenre` ASC) VISIBLE,
  INDEX `fk_Band_has_Genre_Band_idx` (`Band_idBand` ASC) VISIBLE,
  CONSTRAINT `fk_Band_has_Genre_Band`
    FOREIGN KEY (`Band_idBand`)
    REFERENCES `Crowdex`.`Band` (`idBand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Band_has_Genre_Genre1`
    FOREIGN KEY (`Genre_idGenre`)
    REFERENCES `Crowdex`.`Genre` (`idGenre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Crowdex`.`User_has_Event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Crowdex`.`User_has_Event` (
  `User_idUser` INT NOT NULL,
  `Event_idEvent` INT NOT NULL,
  PRIMARY KEY (`User_idUser`, `Event_idEvent`),
  INDEX `fk_User_has_Event_Event1_idx` (`Event_idEvent` ASC) VISIBLE,
  INDEX `fk_User_has_Event_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Event_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `Crowdex`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Event_Event1`
    FOREIGN KEY (`Event_idEvent`)
    REFERENCES `Crowdex`.`Event` (`idEvent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Crowdex`.`FriendRequest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Crowdex`.`FriendRequest` (
  `idFriendRequest` INT NOT NULL AUTO_INCREMENT,
  `Approved` TINYINT NULL DEFAULT 0,
  `Sender_idUser` INT NOT NULL,
  `Receiver_idUser` INT NOT NULL,
  PRIMARY KEY (`idFriendRequest`),
  INDEX `fk_FriendRequest_User1_idx` (`Sender_idUser` ASC) VISIBLE,
  INDEX `fk_FriendRequest_User2_idx` (`Receiver_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_FriendRequest_User1`
    FOREIGN KEY (`Sender_idUser`)
    REFERENCES `Crowdex`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FriendRequest_User2`
    FOREIGN KEY (`Receiver_idUser`)
    REFERENCES `Crowdex`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Crowdex`.`Photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Crowdex`.`Photo` (
  `idPhoto` INT NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(45) NULL,
  `Photo` VARCHAR(255) NOT NULL,
  `User_idUser` INT NOT NULL,
  `Concert_idConcert` INT NOT NULL,
  PRIMARY KEY (`idPhoto`),
  INDEX `fk_Photo_User1_idx` (`User_idUser` ASC) VISIBLE,
  INDEX `fk_Photo_Concert1_idx` (`Concert_idConcert` ASC) VISIBLE,
  CONSTRAINT `fk_Photo_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `Crowdex`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Photo_Concert1`
    FOREIGN KEY (`Concert_idConcert`)
    REFERENCES `Crowdex`.`Concert` (`idConcert`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Crowdex`.`Group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Crowdex`.`Group` (
  `idGroup` INT NOT NULL AUTO_INCREMENT,
  `Event_idEvent` INT NOT NULL,
  `User_idUser_Owner` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NULL,
  `MaxMembers` VARCHAR(45) NULL DEFAULT '10',
  `CreatedAt` TIMESTAMP NULL,
  PRIMARY KEY (`idGroup`),
  INDEX `fk_Group_Event1_idx` (`Event_idEvent` ASC) VISIBLE,
  INDEX `fk_Group_User1_idx` (`User_idUser_Owner` ASC) VISIBLE,
  CONSTRAINT `fk_Group_Event1`
    FOREIGN KEY (`Event_idEvent`)
    REFERENCES `Crowdex`.`Event` (`idEvent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Group_User1`
    FOREIGN KEY (`User_idUser_Owner`)
    REFERENCES `Crowdex`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Crowdex`.`Group_has_User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Crowdex`.`Group_has_User` (
  `Group_idGroup` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  `JoinedAt` TIMESTAMP NULL,
  PRIMARY KEY (`Group_idGroup`, `User_idUser`),
  INDEX `fk_Group_has_User_User1_idx` (`User_idUser` ASC) VISIBLE,
  INDEX `fk_Group_has_User_Group1_idx` (`Group_idGroup` ASC) VISIBLE,
  CONSTRAINT `fk_Group_has_User_Group1`
    FOREIGN KEY (`Group_idGroup`)
    REFERENCES `Crowdex`.`Group` (`idGroup`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Group_has_User_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `Crowdex`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Crowdex`.`Message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Crowdex`.`Message` (
  `idMessage` INT NOT NULL AUTO_INCREMENT,
  `Group_idGroup` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  `Content` VARCHAR(255) NULL,
  `SentAt` TIMESTAMP NULL,
  `EditedAt` TIMESTAMP NULL,
  `DeletedAt` TIMESTAMP NULL,
  PRIMARY KEY (`idMessage`),
  INDEX `fk_Message_Group1_idx` (`Group_idGroup` ASC) VISIBLE,
  INDEX `fk_Message_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_Message_Group1`
    FOREIGN KEY (`Group_idGroup`)
    REFERENCES `Crowdex`.`Group` (`idGroup`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Message_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `Crowdex`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
