-- ==========================
-- CURRENCY
-- ==========================

INSERT INTO Currency (idCurrency, Name, ISO3, Symbol) VALUES
(1, 'Euro', 'EUR', '€'),
(2, 'Libra Esterlina', 'GBP', '£'),
(3, 'Franco Suíço', 'CHF', 'CHF'),
(4, 'Coroa Norueguesa', 'NOK', 'kr'),
(5, 'Coroa Sueca', 'SEK', 'kr'),
(6, 'Coroa Dinamarquesa', 'DKK', 'kr'),
(7, 'Złoty', 'PLN', 'zł'),
(8, 'Coroa Checa', 'CZK', 'Kč'),
(9, 'Forint', 'HUF', 'Ft'),
(10, 'Leu Romeno', 'RON', 'lei'),
(11, 'Lev Búlgaro', 'BGN', 'лв'),
(12, 'Dinar Sérvio', 'RSD', 'дин'),
(13, 'Lira Turca', 'TRY', '₺'),
(14, 'Dólar Americano', 'USD', '$'),
(15, 'Dólar Canadiano', 'CAD', 'C$'),
(16, 'Peso Mexicano', 'MXN', '$'),
(17, 'Real Brasileiro', 'BRL', 'R$'),
(18, 'Peso Argentino', 'ARS', '$'),
(19, 'Peso Chileno', 'CLP', '$'),
(20, 'Peso Colombiano', 'COP', '$'),
(21, 'Iene', 'JPY', '¥'),
(22, 'Won Sul-Coreano', 'KRW', '₩'),
(23, 'Yuan Renminbi', 'CNY', '¥'),
(24, 'Rupia Indiana', 'INR', '₹'),
(25, 'Dólar de Singapura', 'SGD', 'S$'),
(26, 'Dólar Australiano', 'AUD', 'A$'),
(27, 'Dólar Neozelandês', 'NZD', 'NZ$'),
(28, 'Dirham', 'AED', 'د.إ'),
(29, 'Riyal Saudita', 'SAR', '﷼'),
(30, 'Rand', 'ZAR', 'R'),
(31, 'Dirham Marroquino', 'MAD', 'د.م.');

-- ==========================
-- COUNTRY
-- ==========================

INSERT INTO Country (Name, ISO2, Currency_idCurrency) VALUES
('Portugal', 'PT', 1),
('Espanha', 'ES', 1),
('França', 'FR', 1),
('Alemanha', 'DE', 1),
('Itália', 'IT', 1),
('Bélgica', 'BE', 1),
('Países Baixos', 'NL', 1),
('Luxemburgo', 'LU', 1),
('Áustria', 'AT', 1),
('Irlanda', 'IE', 1),
('Finlândia', 'FI', 1),
('Grécia', 'GR', 1),
('Malta', 'MT', 1),
('Chipre', 'CY', 1),
('Eslováquia', 'SK', 1),
('Eslovénia', 'SI', 1),
('Estónia', 'EE', 1),
('Letónia', 'LV', 1),
('Lituânia', 'LT', 1),
('Croácia', 'HR', 1),
('Reino Unido', 'GB', 2),
('Suíça', 'CH', 3),
('Noruega', 'NO', 4),
('Suécia', 'SE', 5),
('Dinamarca', 'DK', 6),
('Polónia', 'PL', 7),
('Chéquia', 'CZ', 8),
('Hungria', 'HU', 9),
('Roménia', 'RO', 10),
('Bulgária', 'BG', 11),
('Sérvia', 'RS', 12),
('Turquia', 'TR', 13),
('Estados Unidos', 'US', 14),
('Canadá', 'CA', 15),
('México', 'MX', 16),
('Brasil', 'BR', 17),
('Argentina', 'AR', 18),
('Chile', 'CL', 19),
('Colômbia', 'CO', 20),
('Japão', 'JP', 21),
('Coreia do Sul', 'KR', 22),
('China', 'CN', 23),
('Índia', 'IN', 24),
('Singapura', 'SG', 25),
('Austrália', 'AU', 26),
('Nova Zelândia', 'NZ', 27),
('Emirados Árabes Unidos', 'AE', 28),
('Arábia Saudita', 'SA', 29),
('África do Sul', 'ZA', 30),
('Marrocos', 'MA', 31);